In [1]:
import math
import numpy as np


# GRADED FUNCTION: basic_sigmoid

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    # (≈ 1 line of code)
    # s = 
    # YOUR CODE STARTS HERE
    s = 1/(1+np.exp(-x))
    
    # YOUR CODE ENDS HERE
    
    return s

In [2]:
print("basic_sigmoid(1)= " +str(basic_sigmoid(1)))


basic_sigmoid(1)= 0.7310585786300049


In [3]:
t_x = np.array([1,2,3])
print(np.exp(t_x))

T_x = np.exp([1,2,3])
print(T_x)

[ 2.71828183  7.3890561  20.08553692]
[ 2.71828183  7.3890561  20.08553692]


In [4]:
t_x = np.array([1,2,3])
print(t_x+3)

[4 5 6]


# Sigmoid Gradient

In [5]:
def sigmoid_derivative(x):
    s = 1/(1+np.exp(-x))
    ds = s*(1-s)
    return ds

In [6]:
t_x = np.array([1,2,3])
print("sigmoid_derivative(t_x) = " +str(sigmoid_derivative(t_x)))
sigmoid_derivative(t_x)

sigmoid_derivative(t_x) = [0.19661193 0.10499359 0.04517666]


array([0.19661193, 0.10499359, 0.04517666])

# Reshaping arrays


In [7]:
def image2vector(image):
    v = image.reshape((image.shape[0]* image.shape[1]*image.shape[2],1))
    return v

In [8]:
t_image = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(t_image)))


image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


## Normalizing rows

In [9]:
def normalize_rows(x):
    x_norm = np.linalg.norm(x,ord =2,axis=1,keepdims=True)
    x = x/x_norm
    return x


In [10]:
x = np.array([[0,3,4],[1,6,4]])

print(" normalizerows(x) = " +str(normalize_rows(x)))

 normalizerows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


# softmax

In [11]:
def softmax(x):
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp,axis=1, keepdims=True)
    s=x_exp/x_sum
    return s

In [12]:
t_x =np.array([[9,5,6,8],[1,4,4,5]])

print("softmax(x) = " + str(softmax(t_x)))


softmax(x) = [[0.69638749 0.01275478 0.03467109 0.25618664]
 [0.01044177 0.20972851 0.20972851 0.57010121]]


# Vecotorization

In [13]:
import time 

x_1 = [9,9,5,5,7,8,9,3,5,6,6,2,8,6,2,1,8]
x_2 = [9,1,7,5,1,2,8,5,5,1,6,9,9,6,2,9,1]

## classic dot product of vectors ##
tic = time.process_time()
dot = 0

for i in range(len(x_1)):
    dot += x_1[i]*x_2[i]

toc = time.process_time()
print("dot = " +str(dot) + "\n ----- computation time =" +str(1000*(toc-tic)) +"ms")

### classic outer product ###

tic = time.process_time()
outer = np.zeros((len(x_1),len(x_2)))

for i in range(len(x_1)):
    for j in range(len(x_2)):
        
        outer[i,j] = x_1[i]*x_2[j]
    
toc = time.process_time()

print("outer = " +str(outer) + "\n ----- computation time =" +str(1000*(toc-tic)) + "ms")


dot = 474
 ----- computation time =0.0ms
outer = [[81.  9. 63. 45.  9. 18. 72. 45. 45.  9. 54. 81. 81. 54. 18. 81.  9.]
 [81.  9. 63. 45.  9. 18. 72. 45. 45.  9. 54. 81. 81. 54. 18. 81.  9.]
 [45.  5. 35. 25.  5. 10. 40. 25. 25.  5. 30. 45. 45. 30. 10. 45.  5.]
 [45.  5. 35. 25.  5. 10. 40. 25. 25.  5. 30. 45. 45. 30. 10. 45.  5.]
 [63.  7. 49. 35.  7. 14. 56. 35. 35.  7. 42. 63. 63. 42. 14. 63.  7.]
 [72.  8. 56. 40.  8. 16. 64. 40. 40.  8. 48. 72. 72. 48. 16. 72.  8.]
 [81.  9. 63. 45.  9. 18. 72. 45. 45.  9. 54. 81. 81. 54. 18. 81.  9.]
 [27.  3. 21. 15.  3.  6. 24. 15. 15.  3. 18. 27. 27. 18.  6. 27.  3.]
 [45.  5. 35. 25.  5. 10. 40. 25. 25.  5. 30. 45. 45. 30. 10. 45.  5.]
 [54.  6. 42. 30.  6. 12. 48. 30. 30.  6. 36. 54. 54. 36. 12. 54.  6.]
 [54.  6. 42. 30.  6. 12. 48. 30. 30.  6. 36. 54. 54. 36. 12. 54.  6.]
 [18.  2. 14. 10.  2.  4. 16. 10. 10.  2. 12. 18. 18. 12.  4. 18.  2.]
 [72.  8. 56. 40.  8. 16. 64. 40. 40.  8. 48. 72. 72. 48. 16. 72.  8.]
 [54.  6. 42. 30.  6. 12. 48

# Vectorizerd version

In [14]:
a = np.array([1,2,3])
b = np.array([1,2,3])

### dot product###

tic=time.process_time()
c = np.dot(a,b)
toc =time.process_time()
print ("the vectorized dot product of c ="+str(c)+"\n ----computation time =" +str(1000 *  (toc-tic)) +"ms")

the vectorized dot product of c =14
 ----computation time =0.0ms


In [15]:
### outer product###

tic=time.process_time()
c = np.outer(a,b)
toc = time.process_time()
print ("the vectorized of outer product of c ="+str(c)+"\n ----computation time =" +str(1000*(toc-tic)) +"ms")

the vectorized of outer product of c =[[1 2 3]
 [2 4 6]
 [3 6 9]]
 ----computation time =0.0ms


In [16]:
## vectorized elementwise multiplication ###


tic=time.process_time()
c = np.multiply(a,b)
toc = time.process_time()
print ("the vectorized multiplication product of c ="+str(c)+"\n ----computation time =" +str(1000*(toc-tic)) +"ms")

the vectorized multiplication product of c =[1 4 9]
 ----computation time =0.0ms


# L1 and L2 functions..

In [23]:
def L1(yhat,y):
    loss = sum(abs(y-yhat))
    return loss




In [25]:
yhat = np.array([.2, .5, .6, .9, .7])
y = np.array([1,0,1,0,1])

print("L1 = " + str(L1(yhat,y)))


L1 = 2.9000000000000004


# L2

In [26]:
def L2(yhat,y):
    loss = sum((y-yhat)**2)
    return loss

yhat = np.array([.9,.6,.2,.1])
y =  np.array([1,0,0,1])

print("L2 ="+str(L2(yhat,y)))
 

L2 =1.2200000000000002
